### PR TITLE
Update MSSA_Automation_Script.ps1

### PR DESCRIPTION
**Pull request by elijk88**
I have added code that creates an AD users.

### CODE REVIEW

**Comment by njlarson40** [comment]
I added my bit. Let me know if we want to add more depth for it

**Comment by elijk88** [comment]
Yes you can, the script creates a user acct and request an existing member group for the placement of the new user.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by elijk88** [comment]
Yes, I will be converting my script into a function in the near future.

**Review by natejakusz08 — CHANGES_REQUESTED** [review]
Could you somehow set an expiration for the account? This is the command I was thinking. If you could add a variable to ask when you want the account to expire I think that would be best. I think it is bad practice to have an account never expire.

Set-ADAccountExpiration -DateTime:"07/03/2022 00:00:00" -Identity:"CN=Fname Lname,OU=IT,DC=Adatum,DC=com" -Server:"LON-DC1.Adatum.com"

**Comment by elijk88** [comment]
Changes have been made to include the user account expiring in 90 days after creation.

**Review by natejakusz08 — APPROVED** [review]

**Pull request merged**
